CREATE TABLE IF NOT EXISTS jik_000t ( --dataset table
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  symbol text not null,
  timeframe text not null,
  decision_time timestamptz,
  decision_price numeric,
  session_hour int,
  day_of_week text,
  lookback_candles int,
  c_open numeric,
  c_high numeric,
  c_low numeric,
  c_close numeric,
  volume numeric,
  return_1 numeric,
  return_3 numeric,
  return_5 numeric,
  return_10 numeric,
  return_20 numeric,
  ema_9_distance_pct numeric,
  ema_20_distance_pct numeric,
  ema_50_distance_pct numeric,
  ema_100_distance_pct numeric,
  ema_200_distance_pct numeric,
  ema_20_above_50 boolean,
  ema_50_above_200 boolean,
  trend_direction text,
  rsi_14 numeric,
  macd_histogram numeric,
  atr_percent numeric,
  candle_range_pct numeric,
  rolling_volatility_20 numeric,
  relative_volume numeric,
  volume_change_5 numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text not null default 'NOT DEFINED',
  updated_by text not null default 'NOT DEFINED',
  is_active boolean not null default true
);

CREATE TABLE IF NOT EXISTS jik_001t ( --decisions/orders table
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  dataset_id uuid REFERENCES jik_000t(id) ON DELETE CASCADE,
  ref_number text,
  status text not null default 'PLANNED', -- PLANNED, OPEN, CLOSED
  side text not null, -- BUY, SELL
  entry_price numeric not null,
  signal_price numeric,
  entry_offset_pct numeric,
  tp_price numeric,
  sl_price numeric,
  tp_algo_id BIGINT,
  sl_algo_id BIGINT,
  close_reason TEXT,
  opportunity_prob numeric not null,
  direction_prob numeric not null,
  created_by text not null default 'NOT DEFINED',
  created_at timestamptz not null default now(),
  updated_by text not null default 'NOT DEFINED',
  updated_at timestamptz not null default now(),
  is_active boolean not null default true
);